### ISSUE TITLE
Marking npm module as deprecated in favour of Prettier's --check option

### ISSUE THREAD

**Issue by kachkaev** [ikatyang/prettylint#204]
Hi @ikatyang! WDYT of marking this module as deprecated given that `prettier --check` option [is out](https://prettier.io/blog/2019/01/20/1.16.0.html#cli)? See https://github.com/hexacta/prettier-check/issues/11 for a similar discussion 😉

**Comment by ikatyang** [comment]
This module is mainly used for the linter-like experience (e.g., `Replace '' with "";⏎ `), which gives you a more detailed message that you'll know what's wrong with your code.

**Comment by kachkaev** [comment]
Ah, right. It'd be nice to see a demo of this output in README – otherwise passers-by like me may think that `prettylint` is just like `prettier-check` or `prettier --check` 😉
