### ISSUE TITLE
Scans node_modules?

### ISSUE THREAD

**Issue by borekb** [ikatyang/prettylint#209]
When I run `prettier --check "**/*.js"`, it finishes after about 5 seconds.

Running `prettylint "**/*.js"` takes forever so I'm wondering if it's linting all my files incl. node_modules?

**Comment by ikatyang** [comment]
Files in `node_modules` are excluded by default, but `.prettierignore` (or `--ignore-path`) takes precedence over it, which is different from the Prettier CLI.

https://github.com/ikatyang/prettylint/blob/abcdf3b16469238d7fe7cf34b6b73f2ff4ae6034/src/cli.ts#L58-L66

**Comment by borekb** [comment]
Do you think the behavior could be updated to match Prettier's? I.e., `node_modules` would be excluded no matter what.

**Comment by ikatyang** [comment]
There is a `--with-node-modules` flag in the Prettier CLI, but I don't think we need it here since explicitness is better than implicitness IMO, especially when you've specified `.prettierignore`.

**Comment by borekb** [comment]
I asked because this experience was relatively confusing: I had `.prettierignore` with this contents:

```
.next
dist
```

This is fine for Prettier – it ignores `.next`, `dist` _and_ `node_modules`, while for prettylint, the presence of this file actually _included_ `node_modules`. That is a confusing behavior, IMO.

**Comment by ikatyang** [comment]
I'm curious, why do you want to use Prettier CLI and prettylint simultaneously? If you'd like to format it, `prettylint --fix` could do the same.

**Comment by ikatyang** [comment]
(IMO, the `--with-node-modules` flag is more confusing since it could conflict with the content in `.prettierignore`.)

**Comment by borekb** [comment]
> I'm curious, why do you want to use Prettier CLI and prettylint simultaneously? If you'd like to format it, `prettylint --fix` could do the same.

Various people in the team use various tools around Prettier like different IDE plugins, and `.prettierignore` and `.prettierrc` should be universal between them. I see prettylint as another tool in this category and my base expectation that the core behavior is the same, whether I agree with some of the Prettier's choices or not (I agree that `--with-node-modules` is somewhat controversial).

**Comment by ikatyang** [comment]
Though I don't like to introduce the `--with-node-modules` flag but it seems it's the only way to solve this issue. PRs welcome.
