### ISSUE TITLE
VSCode integration?

### ISSUE THREAD

**Issue by borekb** [ikatyang/prettylint#210]
Anyone knows how to best consume the output of prettyling in VSCode? Tasks or would this possibly work with some existing extension?

**Comment by borekb** [comment]
With a script in `package.json` that looks like this:

```
"prettylint": "prettylint --format eslint/lib/formatters/stylish --config .prettierrc --ignore-path .prettierignore \"**/*.{ts,tsx,js,jsx,md,json}\""
```

 and this VSCode task config:

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "prettylint",
      "problemMatcher": ["$eslint-stylish"]
    }
  ]
}
```

It's possible to run the task and see the results in the problem view:

<img width="743" alt="screenshot 2019-03-01 at 10 52 42" src="https://user-images.githubusercontent.com/101152/53630351-289c8380-3c10-11e9-9964-40e28989d299.png">

I'm pretty happy with this but will wait for @ikatyang if there's other suggestions before closing this...

**Comment by ikatyang** [comment]
I simply use this module as a CLI tool, haven't tried to use it in VSCode. I have no idea on this topic.

**Comment by borekb** [comment]
Thank you for your quick response. I'm reasonably happy with the tasks integration, hopefully it helps someone.

There's one remaining issue with navigating to files for which I've created a separate issue: https://github.com/ikatyang/prettylint/issues/212.
