### ISSUE TITLE
Stylish formatter should print absolute paths

### ISSUE THREAD

**Issue by borekb** [ikatyang/prettylint#212]
Since 'stylish' formatter has been integrated into ESLint core, it prints absolute paths.

For comparison, this is the output of ESLint:

```
/Users/borekb/demo/theme.js
   1:19  error  Replace `"mdx-deck/themes"` with `'mdx-deck/themes'`        prettier/prettier
```

And this is prettylint:

```
theme.js
   0:18  warning  Replace `"mdx-deck/themes"` with `'mdx-deck/themes'`        prettier/prettier
```

(Interestingly, it also prints different position in the file: `0:18` instead of `1:19` but let's leave that for another time.)

The difference means that VSCode cannot navigate to files from the Problems view because it assumes absolute path: https://github.com/Microsoft/vscode/issues/2202

Could prettylint be updated to produce absolute paths in the output please?

**Comment by ikatyang** [comment]
That's interesting, I actually copy-pasted the description for `filePath` from the ESLint docs:

https://github.com/ikatyang/prettylint/blob/0f171cccf036f9cfd0794246984e621787efd8bd/src/lint.ts#L5-L10

but it seems it somehow changed:

> (https://eslint.org/docs/developer-guide/working-with-custom-formatters#the-result-object)
>
> **filePath**: The absolute path to the file that was linted.

Is this a breaking change for ESLint 5?

**Comment by borekb** [comment]
Probably; the aforementioned VSCode issue https://github.com/Microsoft/vscode/issues/2202 is from 2016 so I'm not sure when that changed but it's certainly absolute paths today.

**Comment by ikatyang** [comment]
PRs welcome.
