### ISSUE TITLE
EditorConfig is not read, producing different results than `prettier --check`

### ISSUE THREAD

**Issue by borekb** [ikatyang/prettylint#214]
Not a big issue but I'm just going to report what I found out after some hair-pulling: I have a pretty well-formatted Markdown like this:

```md
# Test

- This
- is
- a
- list
```

Running `prettylint temp.md` produces empty output as expected but `prettier --check temp.md` reports the file as mis-formatted.

When I apply the changes Prettier wants to do, I found out that it indented the list like this:

```
# Test

-   This
-   is
-   a
-   list
```

I couldn't work out why, only to find out later that Prettier by default parses `.editorconfig` if it exists and ours looks like this:

```
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 2
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
indent_size = 4
trim_trailing_whitespace = false
```

We specify four spaces for Markdown so that nested lists are indented like this:

```md
- Nested
    - list
    - items
```

which is [safer](https://babelmark.github.io/?text=*+Item%0A++++1.+First+Subitem%0A++++2.+Second+Subitem%0A*+Item%0A++++-+Subitem%0A++++-+Subitem%0A*+Item) than [two](https://babelmark.github.io/?text=*+Item%0A++1.+First+Subitem%0A++2.+Second+Subitem%0A*+Item%0A++-+Subitem%0A++-+Subitem%0A*+Item) spaces.

However, Prettier picks this up and "mis-formats" the non-nested list as shown above, which I believe is a bug / undesired behavior reported here: https://github.com/prettier/prettier/issues/5019 (I completely forgot about this issue and was debugging the issue for an hour 🤦‍♂️ 😅).

Anyway, by this experiment, it turns out that prettylint doesn't parse `.editorconfig` by default, giving different results than `prettier --check`.

**Comment by ikatyang** [comment]
> which is safer than two spaces.

That's why we need a spec, which we followed [CommonMark](https://spec.commonmark.org/) at Prettier.

> Anyway, by this experiment, it turns out that prettylint doesn't parse `.editorconfig` by default, giving different results than `prettier --check`.

This is because that the `editorconfig` option from `prettier.resolveConfig(filePath [, options])` is set to `false` by default to avoid breaking change for API consumer when we introduced it.

PRs welcome. (FYI, there is also a `--no-editorconfig` flag in the Prettier CLI.)
