### ISSUE TITLE
Require a newer prettier version

### ISSUE THREAD

**Issue by autarch** [ikatyang/prettylint#273]
This is a great tool but it requires a fairly old version of prettier. There are a lot of fixes and changes in more recent versions that would be good to have. Prettier just released 3.0.0-alpha in August, but I'm not sure when that will be stable. I think for now requiring a 2.0.0+ version would be good.

**Comment by michaelw85** [comment]
When using npm > `8.6` this will start throwing errors if you have prettier v2 installed.
For me v2 seems to be working fine for a long time with prettylint so maybe a new release with updated deps would suffice.
My current work around is to use an npm override:
```
    "overrides": {
        "prettylint": {
            "prettier": "^2.0.0"
        }
    },
```

**Comment by michaelw85** [comment]
This project seems to have become very stale. Anyone stumbling on this ticket, I'm switching to eslint + prettier integration to be able to do the same.
