### ISSUE TITLE
Format only changed files

### ISSUE THREAD

**Issue by azz** [ikatyang/prettylint#64]
I wonder if this is the right place to add this, but I've noticed a bunch of projects like Jest, React and some projects where I work have built scripts to only run Prettier on changed files (since `master`). What if `prettylint --fix` (without a glob) did just that?

The steps React uses to get changed files are here: https://github.com/facebook/react/blob/65aeb701955521551848a8a9cc8e9f279ef2e73c/scripts/shared/listChangedFiles.js#L28-L34

Optionally a `--since` flag could be provided, e.g.: `prettylint --since upstream/dev`

**Comment by azz** [comment]
Or maybe we should just build a special tool for this so we can handle multiple VCSs, etc. 

```bash
$ yarn pretty-quick
🔍 Finding changed files since git ref `upstream/master`.
✍️ Writing to files that aren't 100% pretty.
✨ Done in 0.34s.
```

**Comment by ikatyang** [comment]
We probably need Prettier 2.0 to get it worked so that it won't format unknown file type with default parser, or should we apply the extname logic manually using `getSupportInfo()`?

**Comment by azz** [comment]
Yes it is easy enough to just flatMap out all of the supported extensions.

**Comment by azz** [comment]
https://github.com/azz/pretty-quick :tada:
